### ISSUE TITLE
Knex migrations and SQL upgrade scripts

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#50] opened 2020-06-04 13:42 UTC
## **Request**:
Knex migrations and SQL upgrade scripts.

Discuss some potential issues with knex migrations in production use and discuss alternatives.
Now that we have some live, real money, transfer traffic it is critical to address some concerns.

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner:

**Comment by lewisdaly** [comment] 2020-06-11 01:51
@NicoDuvenage @bushjames is this a duplicate of #27 ?

**Closed** 2020-06-11 16:25 UTC

**Comment by NicoDuvenage** [comment] 2020-06-11 16:28
@lewisdaly and @bushjames : Correct - I labeled it as such and moved to "closed"
