### ISSUE TITLE
Answer the question of how to manage notifications so that a PISP can be registered as an interested party for notification of the success of a transfer

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#48] opened 2020-05-27 10:03 UTC
## **Request**:
Answer the question of how to manage notifications so that a PISP can be registered as an interested party for notification of the success of a transfer

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner:

**Comment by lewisdaly** [comment] 2020-06-11 01:50
@NicoDuvenage @MichaelJBRichards is this a duplicate of #43 ?

**Closed** 2020-06-11 16:23 UTC
Labels: duplicate

**Comment by NicoDuvenage** [comment] 2020-06-11 16:24
@lewisdaly : Correct...I labeled it as such and closed #48
