### ISSUE TITLE
Operation API renaming discussion

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#21] opened 2019-05-16 11:33 UTC
## **Request**:

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: 

## **Notes**:

**Comment by elnyry** [comment] 2020-02-12 19:25
Duplicate of #20

**Closed by elnyry** 2020-02-12 19:25 UTC
Labels: To be Discussed
